### ISSUE TITLE
VR Tracking of controllers and headset does not work

### ISSUE THREAD

**Issue by XYhrihl** [SilvinWillemsen/SIVEtoolkit#1]
Hi, I am currently working on my Bachelor Thesis with ModularVST and the SIVEtoolkit. But I have an issue in VR where the controllers and the headset position is not tracked when I use it with an Oculus Quest 3. I debugged a bit, and it looks like something with the CameraRigs in the `TrackedAliasFacade` or the Sources in the `GameObjectSourceTargetProcessor` does not work properly. 
At the same time, I found that it works in your `SIVEtoolkitTutorial` repository and found this commit eb2bde4ee67b68f894411dc9004d66c4eaf5d687 named `Trying to fix tracked alias facace`. Did this commit fix the issue, and could you explain briefly what you did there? It's quite difficult to understand it from just reading the unity scene files.
Thanks in advance :)

**Comment by SilvinWillemsen** [comment]
Hi XYhrihl, 

Great to hear that you are using the SIVE Toolkit for your Bachelor Thesis! 

Does the simulator work? If it does, you probably need to follow step 10 in Section 3.1 to switch the functionality of the toolkit from using the simulator to using a VR headset. The Tutorial repo probably has this setting on by default.

If it still doesn't work, it might be an issue with the software not being compatible with newer headsets. As you can see in the manual it has only been tested on the Oculus Rift. On the other hand, if you get it to work with the other repo this is probably good news for compatibility, and it might be the problem I mentioned above. 

Let me know if the above works, if not I can try to make it work for an Oculus 2 (which I have access to). 

Cheers!

**Comment by XYhrihl** [comment]
Thanks for the fast reply :) 

My original project setup is a few weeks back, but I think I followed the manual as well as your tutorial video on YouTube. However, I decided to set up a new blank project today where it sometimes worked and sometimes didn't. After switching back and forth a few times, I think I found a pattern of how it works. 

At least now, if I change the XrSetup to UseOculus in the SetCameraRig GameObject and then change the CameraRigs -> Elements 0 from CameraRigs.SpatialSimulator to CameraRigs.UnityXRPluginFramework it worked. 

This is strange because I am pretty sure that this was set to the correct CameraRigs before. Maybe when the SetCameraRig Script made this change automatically, it did not work. Or maybe the change was not correclty applied to the LinkedAliasAssociationCollectionObservableList (Under CameraRigs.TrackedAlias -> Internal -> LinkedAliasCollection ).

However, thanks for replying. Gave me the motivation to dig deeper on this issue and I solved it now :)
Have a good time!

**Comment by SilvinWillemsen** [comment]
Yeah these "handy" coded changes in the editor (which the SetCameraRig script does) sometimes do not work.. hence the extra manual step that you might have to perform. 

Please keep me up to date on your bachelor project! Would love to see the result :)
